### ISSUE TITLE
Roadmap for 0.1

### ISSUE THREAD

**Issue by fesor** [fesor/api-blueprint-parser#1]
- [x] Metadata parsing
- [ ] Name parsing
- [ ] Description parsing
- [ ] Resource Groups Parsing
  - [ ] Name and description parsing
- [ ] Resource Parsing
  - [ ] Name and description parsing
  - [ ] URI Template parsing
  - [ ] Parameters Parsing
  - [ ] Model parsing
  - [ ] Action parsing
  - [ ] Transaction Example parsing

The main goal is to provide 1A7 compatible parser.
